# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/programing/Verilog/CPU_RISCV/CPU_RISCV.cache/wt [current_project]
set_property parent.project_path F:/programing/Verilog/CPU_RISCV/CPU_RISCV.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/programing/Verilog/CPU_RISCV/CPU_RISCV.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/programing/Verilog/CPU_RISCV/defines.v
  F:/programing/Verilog/CPU_RISCV/OpenRISCV.v
  F:/programing/Verilog/CPU_RISCV/ctrl.v
  F:/programing/Verilog/CPU_RISCV/data_ram.v
  F:/programing/Verilog/CPU_RISCV/ex.v
  F:/programing/Verilog/CPU_RISCV/ex_mem.v
  F:/programing/Verilog/CPU_RISCV/id.v
  F:/programing/Verilog/CPU_RISCV/id_ex.v
  F:/programing/Verilog/CPU_RISCV/if_id.v
  F:/programing/Verilog/CPU_RISCV/inst_rom.v
  F:/programing/Verilog/CPU_RISCV/mem.v
  F:/programing/Verilog/CPU_RISCV/mem_wb.v
  F:/programing/Verilog/CPU_RISCV/min_sopc.v
  F:/programing/Verilog/CPU_RISCV/pc_reg.v
  F:/programing/Verilog/CPU_RISCV/regfile.v
  F:/programing/Verilog/CPU_RISCV/min_sopc_tb.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top min_sopc_tb -part xc7k70tfbv676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef min_sopc_tb.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file min_sopc_tb_utilization_synth.rpt -pb min_sopc_tb_utilization_synth.pb"
